### PR TITLE
V0.3.5

### PR DESCRIPTION
**Pull request by dotRData**
added the new function in branch v0.3.5.
let me know if there are any mistakes, this is my first time building at package level.

### CODE REVIEW

**Comment by ELToulemonde** [comment]
Hi thanks for looking into it. 

Here are a few notes/questions:

**Regarding the project**

- I see: +1,899 −1,746: why so many changes? 
- I see new file:  	dataPreparation.Rproj what does it correspond to?
- I can't see Travais and codecov repport on your work? Did you set it up? 

**Regarding the code**
I see:

```
if (is.null(scales)){
    scales <- build_scales(dataSet, cols = "auto", verbose = verbose)
  }
```
I think this part of code is copied from `fastScale`but shouldn't be there any more.

`Would you care to comment on `thresh <- 10^-2` ? 

Great work on documentation and unit tests.


Can you please, comment, complete fix the above points?

Thanks once again.

**Comment by dotRData** [comment]
* about +1,899 −1,746: looks like its re-wrote some of .MD file when compiled again
* dataPreparation.Rproj, corresponds to RStudio Project, i did remove it by adding it to .gitignore
* I didn't setup _Travais_ and _codecov_. will do it and again update the request.

```
if (is.null(scales)){
    scales <- build_scales(dataSet, cols = "auto", verbose = verbose)
  }
```
should not be there as i removed the default value from the function's argument of scales.

i added this `if` condition
``if(abs(sd(dataSet[[col]]) - 1) < thresh & mean(dataSet[[col]]) < thresh)``
so that if the column is not scaled, then do nothing.

**Comment by ELToulemonde** [comment]
Thanks,

I'm wondering if `if(abs(sd(dataSet[[col]]) - 1) < thresh & mean(dataSet[[col]]) < thresh)` wont slow down processing. 
I'm seeing two options:

- Testing it on a limited amount of lines
- Adding a `control` input to able or desable it

**Comment by ELToulemonde** [comment]
Hi,

Did you manage to look into it?
Do you need any help/advice.

**Comment by ELToulemonde** [comment]
No news. I close. 

Don't hesitate to reopen once you have fixed the issues.

**Pull request closed without merging**
